@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1125729761 { 
   	label=SocialNetwork
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   SocialNetwork1125729761[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SocialNetwork</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   people: ArrayList&lt;Person&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addPerson(name: String, email: String, status: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addPostToFriendsWall(nameOne: String, text: String, friendsName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addPostToTheWall(name: String, text: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ checkStatus(name: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ doesFriendshipExist(nameOne: String, nameTwo: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getFriendsPosts(nameOne: String, friendsName: String): Iterator&lt;Post&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPersonByName(name: String): Person</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUserFriends(name: String): Iterator&lt;Person&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ isPersonRegistered(name: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ makeFriendship(nameOne: String, nameTwo: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateStatus(name: String, newStatus: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1907849355 { 
   	label=Person
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Person1907849355[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Person</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   friends: ArrayList&lt;Person&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   posts: ArrayList&lt;Post&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   status: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addFriend(friend: Person)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addPost(post: Post)</TD></TR>
<TR><TD ALIGN="LEFT" >+ isFriendsWith(person: Person): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Main2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2493632 { 
   	label=Post
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Post2493632[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Post</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   author: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   text: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Person1907849355 -> Post2493632[label="posts
[0..*]"];
SocialNetwork1125729761 -> Person1907849355[label="people
[0..*]"];
    
}
@enduml